### ISSUE TITLE
No longer builds with futures-rs 0.3.31

### ISSUE THREAD

**Issue by awused** [StoicDeveloper/mapped_futures#8]
There was a breaking soundness fix in 0.3.31, seems like it's not a trivial fix. https://github.com/rust-lang/futures-rs/pull/2830

```

error[E0310]: the parameter type `K` may not live long enough
   --> src/mapped_futures/task.rs:104:9
    |
104 |         waker_ref(this)
    |         ^^^^^^^^^^^^^^^
    |         |
    |         the parameter type `K` must be valid for the static lifetime...
    |         ...so that the type `K` will meet its required lifetime bounds
    |
help: consider adding an explicit lifetime bound
    |
101 | impl<K: Hash + Eq + 'static, Fut> Task<K, Fut> {
    |                   +++++++++

```

FuturesUnordered had to make a copy of WakerRef without static bounds https://github.com/rust-lang/futures-rs/pull/2830/files#diff-4749c3509fed684159acdaa05f4c30240798a7c201aaa5ecc0e25641b4b6b9d6

**Comment by Meisterian** [comment]
I have added a PR today that may fix this issue:
https://github.com/StoicDeveloper/mapped_futures/pull/7

**Comment by StoicDeveloper** [comment]
resolved https://github.com/StoicDeveloper/mapped_futures/pull/7
